language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
notifications:
  email: false
before_script: 'if [ "$(node -e "console.log(require(''is-iojs''))")" = "false" ]; then npm run build; fi;'
after_success: 'npm run coveralls'